# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QHBoxLayout, QVBoxLayout


class StartWindow(object):
    def setupUi(self, Form, MainWindow):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.layout = QVBoxLayout()

        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.label.setAlignment(Qt.AlignCenter)
        self.layout.addWidget(self.label)

        self.playlist_input = QtWidgets.QLineEdit(Form)
        self.playlist_input.setObjectName("playlist_input")
        self.playlist_input.returnPressed.connect(MainWindow.playlist_submission)
        self.layout.addWidget(self.playlist_input)

        self.playlist_submit_button = QtWidgets.QPushButton(Form)
        self.playlist_submit_button.setObjectName("playlist_submit_button")
        self.playlist_submit_button.clicked.connect(MainWindow.playlist_submission)
        self.layout.addWidget(self.playlist_submit_button)

        self.layout.addStretch(1)  # Add stretchable space at the bottom

        Form.setLayout(self.layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.playlist_submit_button.setText(_translate("Form", "Submit"))
        self.playlist_input.setText(_translate("Form", "playlist"))
        self.label.setText(_translate("Form", "Enter playlist url:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = StartWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
